import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react'

export default function Home() {
  const [ count, setCount ] = useState(0)
  const [ todolist, setTodoList ] = useState(["1", "2", "3"])
  const [ input, setInput ] = useState ('')
  const [ editabledTodo, setEditabledTodo ] = useState(null)

  const editTask = (item, index) => {
    setEditabledTodo(index);
  }

  const handleChange = e => {
    todolist[editabledTodo] = e.target.value
    setTodoList(todolist)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1> Hello </h1>
        <h3> count: {count} </h3>
        <button onClick={() => setCount( count + 1 )}> click </button>

        <input type="text" value={input} onChange={e => setInput(e.target.value)} />
        <button onClick={() => setTodoList(e => [...e, input])}>Add</button>


        { todolist.length > 0 && (
          todolist.map((todo, i) => {
            return (
            <div key={i}>
              <input  defaultValue={todo} onChange={(e) => handleChange(e) } disabled={editabledTodo === i ? false : true}/>
              <button onClick={() => editTask(todo, i)}> Modify </button>
              <button onClick={() => 
                setTodoList(prevArray => prevArray.filter( (item, index) => index !== i))
              }> Delete </button>
            </div>
            )
          })
          
        )}

      </main>

    </div>
  )
}
