import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react'
import Card from '../components/Card'

export default function Home() {



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 > Hello </h1>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center'}}>
          <p>Marketplace</p>
          <p>Menu</p>
          <button> Login </button>
        </div>
        <section style={{display: 'flex', justifyContent: 'center'}}>
        <Card title="test" desc="description" image="https://images.unsplash.com/photo-1639160570277-1c74383a6ec8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDF8ZWRRT21paGVVdFl8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60" price="30" />
        <Card title="test2" desc="description" image="https://images.unsplash.com/photo-1639160570277-1c74383a6ec8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDF8ZWRRT21paGVVdFl8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60" price="30" />
        <Card title="test3" desc="description" image="https://images.unsplash.com/photo-1639160570277-1c74383a6ec8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDF8ZWRRT21paGVVdFl8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60" price="30" />
        <Card title="test4" desc="description" image="https://images.unsplash.com/photo-1639160570277-1c74383a6ec8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDF8ZWRRT21paGVVdFl8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60" price="30" />
        </section>
      </main>

    </div>
  )
}
